---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-immich-secret
  namespace: homelab
spec:
  encryptedData:
    RESTIC_PASSWORD: AgCKvnVXbqheFAyeA1XnBTfznYTg8faeEfaYlX0+6Nh1AAj/ysqwb7g8TQXSbR0V93EswMbQEb9Bu2uy7eOcW8H3qDEgGiSfmOs4nC1voAOka9O8HBimwZ4WD6g3QWZQZyxqlfZnKuDXIk0a4bEUgmYDYiUmz5qlV5SvFxmramsuPRdC8lEYJGjE6+mbunGaio6O1JjSuoKQD5RIPDtYWVAQxBkA2Eu2pZ+X5JK9KLd0aLyIslK5ywyP604VXBNMnKWg1AAEfSizf88Z+qxNPOA07rj/B5R98pQ8U4Oisg7ujA0dH52Kg2z5OmT3N84QCdgr4huj2V5zbCPKRvzDW8Gveue0Lc1v3eAbTsXBBFTv5RMSJ9wD87qFchNyIbq4x+JQBgTqkIB/uT0TCv6uy7MUhq7bS+7D+MibenIN09/YD3IHI1c74i2Ci1NeCCdK8yUbxH5z4pQZBACFxtS9GKzSkenLlJy7WmkxuAJ4x8nIz2oj3MPIa6ADBl2QC2xH14lfyDV+GwZd6HiBereM9JEHTxwZoh+A8C5eoSpVIL3AdytUtxhEVWhhgN5r/eopvoLWy8vMdZpq3OMn6TuW1omsj+UJb4qBNBViUtRIQc90inFcM3KCcXGUIKRAgNpJuUTLW6RvZEA/cEYOZIO+8eiBYIn5h1TcHHj9BSgD7gqr4i7cWLxqJyH7CrcYV9AKk0arluDBqwsramoJC4HLqK8Xzqbx8t579mynn42Me7789zA+qC2st7kYVroOyw==
  template:
    metadata:
      name: restic-immich-secret
      namespace: homelab
    type: Opaque
